language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.4.1
  - 2.3.3
  - 2.2.6
before_script:
  - mysql -u root -e "set global innodb_large_prefix=1;"
  - mysql -u root -e "set global innodb_file_format='Barracuda';"
  - mysql -u root -e "set global innodb_file_per_table=true;"
script:
  - bin/rails db:create
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
